---
- hosts: fedora
  remote_user: fedora
  gather_facts: false
  become_user: root
  become: yes

  tasks:

  - name: WORKAROUND restart cockpit www because of pam issues
    service: name={{ item }} state=restarted
    with_items:
      - cockpit

  - name: WORKAROUND restart machine for idempotent reruns
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=5 timeout=60
    become: no
