---
- hosts: localhost

  vars:
    - server_name_fedora: "{{ lookup('env','server_name_fedora') }}"

    - domain_name_fedora: "{{ lookup('env','domain_name_fedora') }}"

    - os_build_fedora_keypair: "{{ lookup('env','os_build_fedora_keypair') }}"

    - os_build_fedora_image: "{{ lookup('env','os_build_fedora_image') }}"

    - os_build_fedora_flavor: "{{ lookup('env','os_build_fedora_flavor') }}"

    - os_build_fedora_nic0: "{{ lookup('env','os_build_fedora_nic0') }}"

    - os_build_fedora_nic1: "{{ lookup('env','os_build_fedora_nic1') }}"

    - os_fedora_sgroups: "{{ lookup('env','os_fedora_sgroups') }}"


  tasks:

    - debug: msg="Your server name is set to {{ server_name_fedora }}"

    - debug: msg="Your domain name is set to {{ domain_name_fedora }}"

    - debug: msg="Your keypair is set to {{ os_build_fedora_keypair }}"

    - debug: msg="Your image is set to {{ os_build_fedora_image }}"

    - debug: msg="Your nic0 is set to {{ os_build_fedora_nic0 }}"

    - debug: msg="Your nic1 is set to {{ os_build_fedora_nic1 }}"

    - debug: msg="Your security groups are set to {{ os_fedora_sgroups }}"
