---
- name: Create virtual-router object
  command: >
    docker run --net=host opencontrail/config:2.20 /usr/share/contrail-utils/provision_vrouter.py
    --api_server_ip localhost
    --host_name "{{ ansible_hostname }}"
    --host_ip "{{ opencontrail_host_address }}"
  delegate_to: "{{ groups['masters'][0] }}"
