---
- hosts: localhost

  vars:
    - server_name_ubuntu: "{{ lookup('env','server_name_ubuntu') }}"

    - domain_name_ubuntu: "{{ lookup('env','domain_name_ubuntu') }}"

    - os_build_ubuntu_keypair: "{{ lookup('env','os_build_ubuntu_keypair') }}"

    - os_build_ubuntu_image: "{{ lookup('env','os_build_ubuntu_image') }}"

    - os_build_ubuntu_flavor: "{{ lookup('env','os_build_ubuntu_flavor') }}"

    - os_build_ubuntu_nic0: "{{ lookup('env','os_build_ubuntu_nic0') }}"

    - os_build_ubuntu_nic1: "{{ lookup('env','os_build_ubuntu_nic1') }}"

    - os_ubuntu_sgroups: "{{ lookup('env','os_ubuntu_sgroups') }}"


  tasks:

    - debug: msg="Your server name is set to {{ server_name_ubuntu }}"

    - debug: msg="Your domain name is set to {{ domain_name_ubuntu }}"

    - debug: msg="Your keypair is set to {{ os_build_ubuntu_keypair }}"

    - debug: msg="Your image is set to {{ os_build_ubuntu_image }}"

    - debug: msg="Your nic0 is set to {{ os_build_ubuntu_nic0 }}"

    - debug: msg="Your nic1 is set to {{ os_build_ubuntu_nic1 }}"

    - debug: msg="Your security groups are set to {{ os_ubuntu_sgroups }}"
